reschedule:
  name: Reschedule
  description: Creates a new schedule for the battery based on electricity price
  fields:
    battery_soc:
      name: Battery State of Charge
      description: The current state of charge (%) of the battery
      required: true
      advanced: false
      example: 11.3
      default: 10.0
    import_prices_today:
      name: Electricity import prices today
      description: Electricity import prices of today as a list with 24 items, one price per hour
      required: true
      advanced: false
      example: "{{ state_attr('sensor.nordpool', 'today') }}"
      default: "{{ state_attr('sensor.nordpool', 'today') }}"
    import_prices_tomorrow:
      name: Electricity import prices tomorrow
      description: Electricity import prices of tomorrow as a list with 24 items, one price per hour
      required: true
      advanced: false
      example: "{{ state_attr('sensor.nordpool', 'tomorrow') }}"
      default: "{{ state_attr('sensor.nordpool', 'tomorrow') }}"
    export_prices_today:
      name: Electricity export prices today
      description: Electricity export prices of today as a list with 24 items, one price per hour
      required: true
      advanced: false
      example: "{{ state_attr('sensor.nordpool', 'today') }}"
      default: "{{ state_attr('sensor.nordpool', 'today') }}"
    export_prices_tomorrow:
      name: Electricity export prices tomorrow
      description: Electricity export prices of tomorrow as a list with 24 items, one price per hour
      required: true
      advanced: false
      example: "{{ state_attr('sensor.nordpool', 'tomorrow') }}"
      default: "{{ state_attr('sensor.nordpool', 'tomorrow') }}"
    battery_cycle_cost:
      name: Battery cycle cost
      description: Added on top of import prices. Cost of making one kWh charge cycle, which slowly degrades the battery. (battery cost / battery capacity kWh / lifetime charge cycles)
      required: true
      advanced: false
      example: 80
      default: 0
    price_margin:
      name: Price margin
      description: Price margin between import_price + battery_cycle_cost and export_price that must be reached to plan a charge cycle
      required: false
      advanced: false
      example: 20
      default: 0
    low_price_threshold:
      name: Low price threshold
      description: If the battery is not cycled, will charge anyway if the price is below this level
      required: false
      advanced: false
      example: 20
      default: 0

stop:
  name: Stop
  description: Stops the battery

clear:
  name: Clear
  description: Clear the battery schedule

charge:
  name: Charge
  description: Charge the battery now
  fields:
    battery_soc:
      name: Battery State of Charge
      description: The current state of charge (%) of the battery
      required: true
      advanced: false
      example: 5
      default: 5
    power:
      name: Charge power
      description: The power (W) to charge the battery with
      required: true
      advanced: false
      example: 4000
      default: 4000

refresh:
  name: Refresh
  description: Refresh the sensor