default_config:

logger:
  default: info
  logs:
    custom_components.battery_planner: debug

battery_planner:

sensor:
  platform: battery_planner
  currency: SEK
  power_unit: W

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy: