default_config:

logger:
  default: info
  logs:
    custom_components.battery_planner: debug

battery_planner:
  capacity: 7700
  upper_soc_limit: 80
  lower_soc_limit: 20
  max_charge_power: 3000
  max_discharge_power: 3000
  price_margin: 1.5
  cheap_price: 0.3

sensor:
  - platform: battery_planner
    currency: SEK

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy: